export const WELCOME_ROOT = '/'
export const HOME_ROOT = '/home'
export const FAVORITE_ROOT = '/favorite'
export const LIBRARY_ROOT = '/library'
export const PROFILE_ROOT = '/profile'
export const SETTINGS_ROOT = '/settings'
